### ISSUE TITLE
Fix GitHub Actions Cypress Workflow Configuration

### ISSUE THREAD

**Issue by Shaykh102** [Shaykh102/cypress_Odyssey#2]
## Current Issues

The current GitHub Actions workflow configuration (cypress.yaml) has settings that don't match our testing requirements:

1. The workflow is configured to test a local development server when our tests actually run against `https://app.odysseyai.ai/`
2. Unnecessary waiting for local server startup
3. Attempting to start a local server that isn't needed

## Proposed Changes

Replace the current cypress.yaml with:

```yaml
name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          # Add any other environment variables needed for authentication
          CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
          CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
          CYPRESS_ADMIN_API_KEY: ${{ secrets.CYPRESS_ADMIN_API_KEY }}
          CYPRESS_ADMIN_USER_ID: ${{ secrets.CYPRESS_ADMIN_USER_ID }}
```

Key changes:
1. Removed `start` command as we don't need to start a local server
2. Removed `wait-on` as we're testing against a remote service
3. Added environment variables for authentication credentials
4. Kept parallel execution and recording features

## Additional Recommendations

1. Ensure all necessary secrets are configured in GitHub repository settings:
   - CYPRESS_RECORD_KEY
   - GH_TOKEN
   - CYPRESS_ADMIN_EMAIL
   - CYPRESS_ADMIN_PASSWORD
   - CYPRESS_ADMIN_API_KEY
   - CYPRESS_ADMIN_USER_ID

2. Update cypress.config.js to use environment variables:
```javascript
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  e2e: {
    baseUrl: 'https://app.odysseyai.ai',
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    watchForFileChanges: false,
    projectId: "ogemhn",
    retries: {
      runMode: 2,
      openMode: 0
    },
    video: true,
    screenshotOnRunFailure: true
  },
});
```

3. Consider adding environment-specific configurations for different testing environments if needed.
